apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-app
  namespace: argocd
spec:
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/hareeshn903/argocd-example-apps.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default


    